site_name: Technical DRG Archives
theme:
  name: material
  palette:
    primary: amber
    accent: deep purple
  logo: assets/placeholder-logo.png
  favicon: assets/placeholder-favicon.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top

repo_name: Technical-DRG/Technical-DRG-Archives
repo_url: https://github.com/Technical-DRG/Technical-DRG-Archives

plugins:
  - search
  - tags:
      tags_file: tags.md
  - git-revision-date-localized:
      type: iso_datetime

markdown_extensions:
  - abbr
  - admonition
  - footnotes
  - toc:
      permalink: true
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

# For MathJax suport
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Tags: tags.md
